scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["host.docker.internal:9187"]
